AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'
    - 'spec/shared_examples/**/*.rb'

Layout/LineLength:
  Max: 80

Naming/FileName:
  Exclude:
    - lib/rack-on-lambda.rb
    - spec/rack-on-lambda_spec.rb

# TODO: Add documentation and remove the Style/Documentation exception.
Style/Documentation:
  Enabled: false
